Graph
int Graph::totalNodes
int Graph::distance
int Graph::MAX
int Graph::vertices[][]
int Graph::edgeVertices[][]
int** Graph::matrix
QVector<QString> Graph::visitedNodes
QVector<Node> Graph::nodes
bool Graph::visited[][]
Graph::Graph()
Graph::Graph.
Graph::~Graph()
void Graph::AddEdge(QString nodeFrom, QString nodeTo, int edgeWeight)
Graph::AddEdge.
nodeFrom nodeTo edgeWeight Simple member function to add a new edge
References isNode.
void Graph::AddNode(QString nodeName)
Graph::AddNode.
nodeName Adds a new node
void Graph::SetMatrix()
Graph::SetMatrix Sets the matrix with the given specifications.
References GetVertex.
Referenced by MainWindow::MainWindow.
bool Graph::isConnected(QString nodeFrom, QString nodeTo)
bool Graph::isNode(QString nodeName)
Graph::isNode.
node boolean
Referenced by AddEdge.
int Graph::GetWeight(QString nodeFrom, QString nodeTo)
int Graph::GetDistance()
int Graph::GetTotalNodes()
int Graph::GetVertex(QString nodeName)
Graph::GetVertex.
nodeName vertex Finds and returns the vertex associated with a nodeName
Referenced by SetMatrix.
QString Graph::GetNodeName(int vertex)
Graph::GetNodeName.
vertex nodeName at vertext location
Referenced by PerformCompleteDijkstra, MainWindow::MainWindow.
int* Graph::GetVertices()
QVector<Node> Graph::GetNodes()
QVector<QString> Graph::GetVisitedNodes()
void Graph::DFS(QString nodeName, QVector< QString > &stadiums)
Graph::DFS.
nodeName Simple DFS Graphing Function
void Graph::BFS(QString nodeName, QVector< QString > &stadiums)
Graph::BFS.
nodeName Implementation of the BFS graph function
int Graph::PrimMST()
Graph::PrimMST.
distance Returns the distance of the PrimMST
QVector< int > Graph::Dijkstra(int sourceVertex, QVector< QString > &stadiums)
Graph::Dijkstra.
sourceVertex distances Out implementation of the Dijkstra's algorithm
Referenced by PerformFromToDijkstra.
int Graph::PerformCompleteDijkstra(int sourceVertex, int baseCase, QVector< QString > &stadiums)
Graph::PerformCompleteDijkstra.
sourceVertex baseCase Disjkstra's algorithm on a segment of verticies
References GetNodeName.
int Graph::PerformFromToDijkstra(int fromVertex, int toVertex)
Graph::PerformFromToDijkstra.
fromVertex toVertex Dijkstra's algorithm from a vertex to a vertex
References Dijkstra.
QVector< WeightEdge > Graph::sortedIncidentEdges(QString nodeName)
Graph::sortedIncidentEdges.
nodeName sortedEdges Sorts the edges on the graph
Node Graph::GetNodeFromName(QString nodeName)
Graph::GetNodeFromName.
nodeName nodeIT Finds a node based on it's name
bool Graph::isVisited(QString nodeName)
Graph::isVisited.
nodeName boolean Simple function to find out of if a node has been visited
void Graph::dfsUtil(Node node, QVector< QString > &stadiums)
Graph::dfsUtil.
node
int Graph::minKey(int key[], bool mstSet[])
Graph::minKey.
key mstSet min_index A utility function to find the vertex with minimum key value, from the set of vertices not yet included in MST
int Graph::minDistance(QVector< int > distances, bool sptSet[])
Graph::minDistance.
distances sptSet min_index Returns the minimum distance between multiple points
void Graph::DijkstraRecursive(int sourceVertex, int baseCase, QVector< QString > &stadiums)
Graph::DijkstraRecursive.
sourceVertex baseCase A recursive implementation of the Dijkstra algorithm.